services:
  app:
    build:
      context: .
      # dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    networks:
      - app-network
    restart: always
  
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - app-network
    restart: always
  
  db2:
    image: redis:8-alpine
    ports:
      - "6380:6379"
    networks:
      - internal-network
    restart: always

  hybrid:
    image: redis:7-alpine
    ports:
      - "6381:6379"
    networks:
      - app-network
      - internal-network
    restart: always

networks:
  app-network:
  internal-network:
    internal: true
