version: "3.9"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=textinput
      - DB_PASSWORD=textinput1234
      - DB_NAME=textinputdb
    depends_on:
      - db
    command: ["./wait_for_db.sh", "uvicorn", "app:app", "--host", "0.0.0.0", "--port", "5000"]
    #command: ["./wait_for_db.sh", "python", "app.py"]

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: superroot
      MYSQL_DATABASE: textinputdb
      MYSQL_USER: textinput
      MYSQL_PASSWORD: textinput1234
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
