name: Daily Pylint Schedule Workflow

on:
  push: 
    branches-ignore:
      - main
      - dev
    pull_request:
      branches:
      - main
      - dev

  schedule: 
   -cron: " 0 19 * * * "  #Runs at 7Pm
  workflow_dispatch: # Allow manual trigger
 
permissions:
  contents: read

jobs:
  run-job:
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout code
        uses: actions/checkout@v4
       
      - name: run task on 
        run: echo "run on schedule or push (excluding main or dev branch)" && 
        PR to main and dev

        
          pip install -r requirements.txt

      - name: Analysing the code with pylint
        run: |
          pylint $(git ls-files '*.py')
